###
POST http://localhost:8080/location/def456/now
Content-Type: application/json;charset=UTF-8

{
	"lat": 12.34,
	"lng": 56.78
}

####

GET http://localhost:8080/location/def456

####

DELETE http://localhost:8080/location/xyz987
