###
POST http://localhost:8080/location/g4355678dsffd14424/now
Content-Type: application/json;charset=UTF-8

{
	"lat": 12.34,
	"lng": 56.78
}


####

###
POST http://localhost:8080/location/g4355678dsffd14424/now
Content-Type: application/json;charset=UTF-8

{
	"lat": 12.34,
	"lng": 56.79
}

####

GET http://localhost:8080/location/g4355678dsffd14424


####

GET http://localhost:8080/location/g4355678dsffd14424?max=2


####

DELETE http://localhost:8080/location/g4355678dsffd14424
